-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 00:37:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NewsNet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NewsNet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NewsNet` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `NewsNet` ;

-- -----------------------------------------------------
-- Table `NewsNet`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewsNet`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `master_id` INT UNSIGNED NULL,
  `name` VARCHAR(256) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `enable` TINYINT NOT NULL,
  `permission` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_user_user1_idx` (`master_id` ASC),
  CONSTRAINT `fk_user_user1`
    FOREIGN KEY (`master_id`)
    REFERENCES `NewsNet`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewsNet`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewsNet`.`categoria` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NewsNet`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NewsNet`.`post` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `filename` VARCHAR(255) NOT NULL,
  `hidden` TINYINT NOT NULL,
  `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `categoria_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Post_User_idx` (`user_id` ASC),
  UNIQUE INDEX `filename_UNIQUE` (`filename` ASC),
  INDEX `fk_post_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `NewsNet`.`user` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_post_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `NewsNet`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
